sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t yash028/docker-react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true yash028/docker-react-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-frontend"
  env: "Dockerreactfrontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-169640583188"
  bucket_path: "docker-react-frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"