sudo: required

services:
  - docker

before_install:
  - docker build -t yash028/docker-react-frontend -f Dockerfile.dev .

script:
  - docker run yash028/docker-react-frontend npm run test -- --coverage